### ISSUE TITLE
TODO in 19_http_server

### ISSUE THREAD

**Issue by ichang0301** [ichang0301/learn-golang#13]
## TODO in 19_http_server

- [x]  Pick a store (Bolt? Mongo? Postgres? File system?) 
- [x] make structs implement `PlayerStore`
- [x] plug it into `main`

**Comment by ichang0301** [comment]
https://github.com/ichang0301/learn-golang/pull/15
